# Generated by Django 4.2.3 on 2023-11-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.CharField(default='auxiliar', max_length=50),
        ),
    ]
