# Generated by Django 4.2.3 on 2023-11-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_userfcm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
