# Generated by Django 4.2.3 on 2023-11-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_alter_user_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfcm',
            name='token',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
